import { useEffect, useMemo, useState } from 'react'
import { getCatalog, getHistory, getLatest } from './data'
import { challengeFor, pacificSeed, ROUND_CAPITAL, roundOutcome } from './game'
import type { Catalog, LatestPrices, PriceHistory } from './types'

type Saved = { allocations: number[]; revealed: number }
const money = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
const percent = new Intl.NumberFormat('en-US', { style: 'percent', maximumFractionDigits: 1, signDisplay: 'always' })

export function App() {
  const seed = new URLSearchParams(location.search).get('seed') || pacificSeed()
  const [catalog, setCatalog] = useState<Catalog>(); const [latest, setLatest] = useState<LatestPrices>(); const [histories, setHistories] = useState<Record<string, PriceHistory>>({}); const [saved, setSaved] = useState<Saved>({ allocations: [5000, 5000, 5000], revealed: 0 }); const [error, setError] = useState('')
  useEffect(() => { Promise.all([getCatalog(), getLatest()]).then(([c, l]) => { setCatalog(c); setLatest(l) }).catch((e: Error) => setError(e.message)) }, [])
  const challenge = useMemo(() => catalog ? challengeFor(seed, catalog) : undefined, [catalog, seed])
  useEffect(() => { if (!challenge || !catalog) return; const key = `ttsm:${catalog.version}:${seed}`; const restored = localStorage.getItem(key); setSaved(restored ? JSON.parse(restored) : { allocations: [5000, 5000, 5000], revealed: 0 }); const paths = [...challenge.pairs.flatMap((pair) => [pair.left.history, pair.right.history]), catalog.benchmark]; Promise.all(paths.map(getHistory)).then((items) => setHistories(Object.fromEntries(items.map((item) => [item.symbol, item])))).catch((e: Error) => setError(e.message)) }, [challenge, catalog, seed])
  useEffect(() => { if (catalog) localStorage.setItem(`ttsm:${catalog.version}:${seed}`, JSON.stringify(saved)) }, [saved, catalog, seed])
  if (error) return <main className="shell"><p className="eyebrow">Data unavailable</p><h1>Time Travel Stock Market</h1><p>{error}</p></main>
  if (!challenge || !latest) return <main className="shell"><p className="eyebrow">Loading market archive</p><h1>Time Travel Stock Market</h1></main>
  const current = Math.min(saved.revealed, 2); const allRevealed = saved.revealed === 3; const pair = challenge.pairs[current]; const ready = pair && histories[pair.left.symbol] && histories[pair.right.symbol]
  const results = challenge.pairs.map((p, index) => histories[p.left.symbol] && histories[p.right.symbol] ? roundOutcome(histories[p.left.symbol], histories[p.right.symbol], challenge.date, latest.prices, saved.allocations[index]) : undefined)
  const total = results.reduce((sum, result) => sum + (result?.total || 0), 0); const optimal = results.reduce((sum, result) => sum + (result?.optimal || 0), 0); const capital = ROUND_CAPITAL * 3
  const benchmarkStart = histories['^SP500TR']?.prices[challenge.date]; const benchmark = benchmarkStart ? capital * latest.prices['^SP500TR'] / benchmarkStart : 0
  const update = (value: number) => setSaved((state) => ({ ...state, allocations: state.allocations.map((old, i) => i === current ? value : old) })); const reveal = () => setSaved((state) => ({ ...state, revealed: Math.min(3, state.revealed + 1) }))
  const share = async () => { const text = `I turned ${money.format(capital)} into ${money.format(total)} in Time Travel Stock Market. Can you do better? ${location.href}`; await navigator.clipboard?.writeText(text); window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}`, '_blank', 'noopener,noreferrer') }
  const travelDate = new Date(`${challenge.date}T12:00:00`).toLocaleDateString('en-US', { dateStyle: 'long' })
  return <main className="shell"><header><p className="eyebrow">Market archive · prices as of {latest.asOf}</p><h1>Time Travel<br /><i>Stock Market</i></h1><p className="lede">You’ve arrived in <strong className="travel-date">{travelDate}</strong>. You have $10,000. Where do you put it?</p></header>
    {!allRevealed && pair && <section className="card" aria-live="polite"><p className="round">Round {current + 1} of 3 · {pair.left.industry}</p><div className="companies"><div><span>{pair.left.symbol}</span><h2>{pair.left.name}</h2><strong className="investment">{money.format(saved.allocations[current])}</strong></div><b>vs</b><div><span>{pair.right.symbol}</span><h2>{pair.right.name}</h2><strong className="investment">{money.format(ROUND_CAPITAL - saved.allocations[current])}</strong></div></div>{ready ? <><label htmlFor="allocation"><span>Move right to invest more in {pair.right.symbol}</span><em>{pair.left.symbol} ← allocation → {pair.right.symbol}</em></label><input id="allocation" type="range" min="0" max="10000" step="100" value={ROUND_CAPITAL - saved.allocations[current]} onChange={(e) => update(ROUND_CAPITAL - Number(e.target.value))} disabled={saved.revealed > current} />{saved.revealed > current && results[current] && <Result result={results[current]!} left={pair.left.symbol} right={pair.right.symbol} />}{saved.revealed === current && <button onClick={reveal}>Lock allocation</button>}</> : <p>Loading price history…</p>}</section>}
    {allRevealed && <section className="card final"><p className="round">Your time-travel ledger</p><h2>{money.format(total)}</h2><p>from {money.format(capital)} invested across three decisions.</p><dl><div><dt>Your result</dt><dd>{money.format(total)}</dd></div><div><dt>Perfect foresight</dt><dd>{money.format(optimal)}</dd></div><div><dt>S&P 500 total return</dt><dd>{money.format(benchmark)}</dd></div></dl><PerformanceGauges player={total - capital} optimal={optimal - capital} benchmark={benchmark - capital} /><h3>How the stocks changed</h3><table><thead><tr><th>Pair</th><th>Left stock</th><th>Right stock</th></tr></thead><tbody>{challenge.pairs.map((round, index) => { const result = results[index]!; const leftWon = result.leftReturn > result.rightReturn; const rightWon = result.rightReturn > result.leftReturn; return <tr key={`pair-${index}`}><td><span>Pair {index + 1}</span><small>{round.left.symbol} vs {round.right.symbol}</small></td><td className={leftWon ? 'winner-cell' : ''}><strong>{round.left.symbol}</strong> {round.left.name}<em className={result.leftReturn >= 0 ? 'gain' : 'loss'}>{percent.format(result.leftReturn)}</em>{leftWon && <i>Winner</i>}</td><td className={rightWon ? 'winner-cell' : ''}><strong>{round.right.symbol}</strong> {round.right.name}<em className={result.rightReturn >= 0 ? 'gain' : 'loss'}>{percent.format(result.rightReturn)}</em>{rightWon && <i>Winner</i>}</td></tr> })}</tbody></table><button onClick={share}>Share your result</button><button className="quiet" onClick={() => setSaved({ allocations: [5000, 5000, 5000], revealed: 0 })}>Replay this seed</button></section>}
  </main>
}
function Result({ result, left, right }: { result: ReturnType<typeof roundOutcome>; left: string; right: string }) { return <div className="result"><p>{left} {percent.format(result.leftReturn)} · {right} {percent.format(result.rightReturn)}</p><strong>Your result: {money.format(result.total)}</strong><small>Perfect foresight: {money.format(result.optimal)}</small></div> }
function PerformanceGauges({ player, optimal, benchmark }: { player: number; optimal: number; benchmark: number }) { if (optimal <= 0) return <section className="gauges"><h3>Performance gauges</h3><p>Neither stock allocation produced a positive return over this period.</p></section>; const playerPercent = Math.max(0, Math.min(100, player / optimal * 100)); const benchmarkBeatsStocks = benchmark > optimal; const comparisonPercent = Math.max(0, Math.min(100, (benchmarkBeatsStocks ? optimal / benchmark : benchmark / optimal) * 100)); return <section className="gauges"><h3>Performance gauges</h3><Gauge label="Your share of possible stock earnings" value={playerPercent} primary="You" comparison="Perfect picks" /><Gauge label={benchmarkBeatsStocks ? 'Best stock picks vs. S&P 500' : 'S&P 500 vs. best stock picks'} value={comparisonPercent} primary={benchmarkBeatsStocks ? 'Best picks' : 'S&P 500'} comparison={benchmarkBeatsStocks ? 'S&P 500' : 'Best picks'} /></section> }
function Gauge({ label, value, primary, comparison }: { label: string; value: number; primary: string; comparison: string }) { return <div className="gauge"><div className="gauge-label"><span>{label}</span><strong>{Math.round(value)}%</strong></div><div className="gauge-track" role="img" aria-label={`${primary} achieved ${Math.round(value)} percent of ${comparison}`}><div className="gauge-fill" style={{ width: `${value}%` }} /></div><div className="gauge-key"><span>{primary}</span><span>{comparison}</span></div></div> }
